### ISSUE TITLE
[BUG]: reverse_image_search server is stuck to install packages

### ISSUE THREAD

**Issue by zhenzi0322** [milvus-io/bootcamp#1071]
reverse_image_search server is stuck, if you execute the load you can't execute count again, you have to wait until the load is loaded to execute.

![image](https://user-images.githubusercontent.com/34839719/189597764-38f0da0c-82e0-49a1-b388-615facf4b5f7.png)

```
INFO:     192.168.0.102:52625 - "POST /img/load HTTP/1.1" 500 Internal Server Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 215, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 70, in load_images
    total_num = do_load(item.Table, item.File, MODEL, MILVUS_CLI, MYSQL_CLI)
  File "/app/src/operations/load.py", line 59, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/app/src/milvus_helpers.py", line 73, in insert
    sys.exit(1)
SystemExit: 1
```

**Comment by shiyu22** [comment]
Seems that it was installing opencv-python, so please check the net.

BTW, you can run `docker exec -ti img-search-webserver bash` and run `pip install opencv-python` manually with your source.

**Comment by zhenzi0322** [comment]
> Seems that it was installing opencv-python, so please check the net.
> 
> BTW, you can run `docker exec -ti img-search-webserver bash` and run `pip install opencv-python` manually with your source.

Ok

**Comment by zhenzi0322** [comment]
> Seems that it was installing opencv-python, so please check the net.
> 
> BTW, you can run `docker exec -ti img-search-webserver bash` and run `pip install opencv-python` manually with your source.

That doesn't seem to be the reason, I reloaded the data once after all the downloads were done and still couldn't request /img/count

**Comment by zhenzi0322** [comment]
It was stuck for five minutes.   As long as /img/load is requested first, no other interface can be requested

**Comment by shiyu22** [comment]
After you have installed all the package, you can restart the webserver container and rerun.

**Comment by zhenzi0322** [comment]
> After you have installed all the package, you can restart the webserver container and rerun.

I've finished the installation and my first request for /img/count comes back fine, if I request /img/load and then request /img/count again it gets stuck. Then I have to restart the webserver container before I can request /img/count

**Comment by shiyu22** [comment]
Got it, will close issue.
