### ISSUE TITLE
[BUG]: Hi I am trying to run the server without docker and its not working. Can you please tell on which port the server is running after installing milvus with YUM on centOS

### ISSUE THREAD

**Issue by rahul-iitk** [milvus-io/bootcamp#1112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[dsuser@zmplhdpegapp01 rahul]$ python3 hello_milvus.py

=== start connecting to Milvus     ===

Traceback (most recent call last):
  File "/data/Python-3.7.9/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 90, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=3)
  File "/data/Python-3.7.9/lib/python3.7/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/data/Python-3.7.9/lib/python3.7/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello_milvus.py", line 33, in <module>
    connections.connect("default", host="localhost", port="80")
  File "/data/Python-3.7.9/lib/python3.7/site-packages/pymilvus/orm/connections.py", line 156, in connect
    conn = connect_milvus(**kwargs)
  File "/data/Python-3.7.9/lib/python3.7/site-packages/pymilvus/orm/connections.py", line 144, in connect_milvus
    gh._wait_for_channel_ready()
  File "/data/Python-3.7.9/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 93, in _wait_for_channel_ready
    raise BaseException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._uri}. Timeout')
pymilvus.client.exceptions.BaseException: <BaseException: (code=2, message=Fail connecting to server on localhost:80. Timeout)>
[dsuser@zmplhdpegapp01 rahul]$ FATAL ERROR: Server unexpectedly closed network connection
Connection to 172.23.5.158 closed.

### Software version

```markdown
Milvus: [e.g. 2.1.0rc1]
Server: [e.g. 2.1.0]
Client: [e.g. 2.1.0]
```

**Comment by shiyu22** [comment]
The default port is 19530, you can try [hello Milvus](https://milvus.io/docs/v2.1.x/example_code.md) first to ensure that Milvus is started successfully.
