### ISSUE TITLE
KeyError: 'current'

### ISSUE THREAD

**Issue by GaoJian1102** [milvus-io/bootcamp#159]
2020-03-31 08:24:34,394 - app - ERROR - Exception on /api/v1/process [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in thread_status_api
    return "current: {}, total: {}".format(cache['current'], cache['total'])
  File "/usr/local/lib/python3.6/dist-packages/diskcache/core.py", line 1262, in __getitem__
    raise KeyError(key)
KeyError: 'current'

docker image : 
chenglong555/pic_search_demo_web:0.2.0  
chenglong555/pic_search_demo:0.5.1     
milvusdb/milvus:0.6.0-cpu-d120719-2b40dd

**Comment by alono88** [comment]
Any news regrading this issue? I encountered the same error today. @GaoJian1102 did you solve it?

**Comment by JackLCL** [comment]
Can  I  have a look at  your start command of your webserver docker?

**Comment by JackLCL** [comment]
Maybe there is a problem with your image_path configuration.

**Comment by alono88** [comment]
@JackLCL It s eems I'm getting the error again while the paths are correct (I can connect to the webserver docker and view the mounted folder):

'''docker run -d --name zilliz_search_images_demo -v /home/ubuntu/tmp1/:/tmp/pic1 -p 35000:5000 -e "DATA_PATH=/tmp/images-data" -e "MILVUS_HOST=172.31.7.56" milvusbootcamp/pic-search-webserver:0.1.0'''

**Comment by JackLCL** [comment]
@alono88 What version of milvus are you using? If you are using Milvus0.7.0, you need to use webserver:0.3.0.

**Comment by alono88** [comment]
It still doesn't work. Tried Milvus0.6.0 with bootcamp webserver and webclient 0.1.0 and I get errors when loading in some of the images although they are .png images and I cannot perform similarity search due to another error in src/service/search.py do_search function that returns the wrong number of arguments.

**Comment by JackLCL** [comment]
@alono88  I suggest you to use milvus 0.7.0 to search for pictures. And corresponding webserver version is 0.3.0.  And corresponding webclient version is 0.1.0.   
Reference link: https://github.com/milvus-io/bootcamp/tree/0.7.0/solutions/pic_search

**Comment by limjoe** [comment]
webserver 0.4.0, client 0.1.0 也遇到这个问题，没法上传 datasets
