### ISSUE TITLE
Function connect has been deprecated

### ISSUE THREAD

**Issue by xxxpsyduck** [milvus-io/bootcamp#242]
```bash
root@0bab3a1c5bbe:/var/lib/milvus/bootcamp/EN_solutions/recommender_system# python3 infer_milvus.py -a 6 -g 1 -j 10 -i
get infer vectors finished!
Function connect has been deprecated
2020-06-30 08:41:37,507-ERROR: Function connect has been deprecated
Traceback (most recent call last):
  File "infer_milvus.py", line 202, in <module>
    main(sys.argv[1:], use_cuda)
  File "infer_milvus.py", line 198, in main
    milvus_test([usr_features.tolist()], IS_INFER, mov_features, ids)
  File "infer_milvus.py", line 117, in milvus_test
    status = milvus.connect(**param)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py", line 29, in inner
    raise DeprecatedError(error_str)
milvus.client.exceptions.DeprecatedError: Function connect has been deprecated
```

**Comment by shiyu22** [comment]
Did you start Milvus? And what version is Milvus?

After starting Milvus, make ensure the  _HOST and  _PORT parameters in the infer_milvus.py code are consistent with the IP and port of Milvus that has been started.
