### ISSUE TITLE
milvus_helpers.py ｜ has_collection ｜ 36 ｜ Failed to load data to Milvus: 'NoneType' object has no attribute 'fetch'

### ISSUE THREAD

**Issue by longer3** [milvus-io/bootcamp#607]
**Describe the issue**
insert vectors to milvus collection return error 

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1.start milvus
2.start bootcamps/solutions/reverse_image_search
3.waitting 
4.sometimes it happen

**Expected behavior**
insert vectors to milvus collection

**Screenshots**
Traceback (most recent call last):
  File "/root/Deploy/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 34, in has_collection
    return utility.has_collection(collection_name)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/utility.py", line 212, in has_collection
    return _get_connection(using).has_collection(collection_name)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 278, in has_collection
    with self._connection() as handler:
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 162, in _connection
    return self._pool.fetch()
AttributeError: 'NoneType' object has no attribute 'fetch'

**Software version (please complete the following information):**
 - Milvus: [2.0.0rc4]
 - Server: [2.0.0]
 - Client: [2.0.0]

**Additional context**

**Comment by shiyu22** [comment]
not activate.
