### ISSUE TITLE
milvus server exit unnormally

### ISSUE THREAD

**Issue by longer3** [milvus-io/bootcamp#608]
**Describe the issue**
milvus server exit unnormally

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1. start standalone milvus by docker-compose
2. start reverse_image_search
3. waiting
4. docker-compose logs  [INFO] [logger.go:48] ["transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""]
5. milvus server exit
6. milvus_helpers.py ｜ has_collection ｜ 36 ｜ Failed to load data to Milvus: Fail connecting to server on 127.0.0.1:19530. Timeout

**Expected behavior**

**Screenshots**
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/usr/local/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.6/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.6/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.6/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.6/site-packages/fastapi/routing.py", line 215, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.6/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 152, in search_images_by_url
    obj_list = do_search_all(table_name, img_path, MODEL, MILVUS_CLI, MYSQL_CLI)
  File "/data/soft/reverse_image_search/quick_deploy/server/src/operations/search.py", line 27, in do_search_all
    vectors = milvus_client.search_vectors(table_name, [feat], TOP_K)
  File "/data/soft/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 101, in search_vectors
    self.set_collection(collection_name)
  File "/data/soft/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 23, in set_collection
    if self.has_collection(collection_name):
  File "/data/soft/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 37, in has_collection
    sys.exit(1)
SystemExit: 1
2021-08-27 14:31:52,380 ｜ ERROR ｜ grpc_handler.py ｜ ping ｜ 338 ｜ Retry to connect server 127.0.0.1:19530 failed.
2021-08-27 14:31:52,380 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 77 ｜ 
Addr [127.0.0.1:19530] has_collection
Excepted error: Fail connecting to server on 127.0.0.1:19530. Timeout
	{'API start': '2021-08-27 14:31:21.378999', 'Exception': '2021-08-27 14:31:52.380624'}
2021-08-27 14:31:52,380 ｜ ERROR ｜ milvus_helpers.py ｜ has_collection ｜ 36 ｜ Failed to load data to Milvus: Fail connecting to server on 127.0.0.1:19530. Timeout

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc4]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]

**Comment by shiyu22** [comment]
not activate
