### ISSUE TITLE
🔥 how to run milvus docker?

### ISSUE THREAD

**Issue by yfq512** [milvus-io/bootcamp#637]
## I only find README from version=1.1.0,and I have some question:
```
$ wget -P /home/$USER/milvus/conf https://raw.githubusercontent.com/milvus-io/milvus/v1.1.0/core/conf/demo/server_config.yaml
$ sudo docker run -d --name milvus_cpu_1.1.0 \
-p 19530:19530 \
-p 19121:19121 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:1.1.0-cpu-d050721-5e559c
```
- 1. How to make "/home/$USER/milvus" directory?
- 2. I have tryed run docker follow README from version=1.1.0, but I'am failed for can't find /home/$USER/milvus/conf directory(and docker exited). especially, I tried to run it many times again, and it failed(and docker exited), but the docker logs shows that: Milvus server exit...
# Looking forward to your reply, thanks!

**Comment by shiyu22** [comment]
Actually, you can install Milvus 2.0-RC5 refer to https://milvus.io/docs/v2.0.0/install_standalone-docker.md

**Comment by yfq512** [comment]
I install Milvus 2.0-RC5 refer to https://milvus.io/docs/v2.0.0/install_standalone-docker.md, but I'am failed.
I have run docker:
```
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                             PORTS                      NAMES
94884a540c95        milvusdb/milvus:v2.0.0-rc5-hotfix1-20210901-9e0b2cc   "/tini -- milvus run…"   19 seconds ago      Up 17 seconds                      0.0.0.0:19530->19530/tcp   milvus-standalone
0369ee7eb2db        minio/minio:RELEASE.2020-12-03T00-03-10Z              "/usr/bin/docker-ent…"   19 seconds ago      Up 18 seconds (health: starting)   9000/tcp                   milvus-minio
da96f3327395        quay.io/coreos/etcd:v3.5.0                            "etcd -advertise-cli…"   19 seconds ago      Up 18 seconds                      2379-2380/tcp              milvus-etcd
```
I try connect to Milvus Server:
```
>>> from pymilvus import connections
>>> connections.connect("default", host='localhost', port='19530')
Retry to connect server localhost:19530 failed.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 336, in ping
    ft.result(timeout=timeout)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/pymilvus/orm/pymilvus_orm/connections.py", line 158, in connect
    conn = connect_milvus(**kwargs)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/pymilvus/orm/pymilvus_orm/connections.py", line 148, in connect_milvus
    return Milvus(tmp_host, tmp_port, handler, pool, **tmp_kwargs)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/pymilvus/client/stub.py", line 125, in __init__
    self._update_connection_pool(channel=channel)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/pymilvus/client/stub.py", line 172, in _update_connection_pool
    self._pool = SingletonThreadPool(self._pool_uri, channel=channel, **self._pool_kwargs)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/pymilvus/client/pool.py", line 227, in __init__
    self._prepare()
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/pymilvus/client/pool.py", line 232, in _prepare
    conn.client().ping()
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 348, in ping
    raise NotConnectError('Fail connecting to server on {}. Timeout'.format(self._uri))
pymilvus.client.exceptions.NotConnectError: Fail connecting to server on localhost:19530. Timeout
```

**Comment by shiyu22** [comment]
It looks like Milvus is running successfully, and can you try to use the IP address rather than `localhost`.

**Comment by yfq512** [comment]
@shiyu22 Still not working.

**Comment by yfq512** [comment]
@shiyu22 Is there any restriction on the system, my system is macOS

**Comment by shiyu22** [comment]
Actually, I can run it in Mac, and can you run [hello_milvus](https://milvus.io/docs/v2.0.0/example_code.md)?

Please make sure your internet connection is available and also that the port is open, and run `ping localhost:19530`.

**Comment by yfq512** [comment]
I can't run hello_milvus for "Fail connecting to server on localhost:19530. Timeout".
"telnet localhost 19530", shows it work well.

**Comment by shiyu22** [comment]
I think you do start the Milvus server, but cannot connect it, you can refer to [this issue](https://github.com/milvus-io/milvus/issues/1664) although it's for Milvus1.x.

Maybe you can try to restart Milvus server, and if it still reports this error, please submit an issue to [milvus repo](https://github.com/milvus-io/milvus/issues/new/choose).

**Comment by ucas010** [comment]
hi ,dear
what does it mean ?
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \

-v /home/** is what and the /var/** is what ?
thx
