### ISSUE TITLE
[BUG]: milvus2.0 text_search_engine docs FastApi /text/search 500 (Internal Server Error)

### ISSUE THREAD

**Issue by anykkk** [milvus-io/bootcamp#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/48540503/137466171-1bd1d072-9af7-48fc-b3c3-d5fe123fb1c1.png)
![image](https://user-images.githubusercontent.com/48540503/137466577-87841418-9acf-4ee6-9f80-6dc9745ca4f5.png)
2021-10-15 17:35:48,139 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 61 ｜ Error: <BaseException: (code=1, message=round_decimalnot found in search_params)>
2021-10-15 17:35:48,139 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 61 ｜ Error: <BaseException: (code=1, message=round_decimalnot found in search_params)>
2021-10-15 17:35:48,139 ｜ ERROR ｜ milvus_helpers.py ｜ search_vectors ｜ 105 ｜ Failed to search vectors in Milvus: <BaseException: (code=1, message=round_decimalnot found in search_params)>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/haojy/bootcamp-master/solutions/text_search_engine/quick_deploy/server/src/milvus_helpers.py", line 100, in search_vectors
    res=self.collection.search(vectors, anns_field="embedding", param=search_params, limit=top_k)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 610, in search
    partition_names, output_fields, timeout, **kwargs)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/stub.py", line 1057, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 96, in handler
    return func(self, *args, **kwargs)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 640, in search_with_expression
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 606, in _execute_search_requests
    raise pre_err
  File "/home/haojy/.local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 597, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=round_decimalnot found in search_params)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haojy/.local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/haojy/.local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/haojy/.local/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/haojy/.local/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/haojy/.local/lib/python3.7/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 86, in do_search_api
    ids,title, text, distances = search_in_milvus(table_name,query_sentence, MILVUS_CLI, MYSQL_CLI)
  File "/home/haojy/bootcamp-master/solutions/text_search_engine/quick_deploy/server/src/operations/search.py", line 35, in search_in_milvus
    results = milvus_cli.search_vectors(table_name,query_list,TOP_K)
  File "/home/haojy/bootcamp-master/solutions/text_search_engine/quick_deploy/server/src/milvus_helpers.py", line 106, in search_vectors
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haojy/.local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/haojy/.local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/haojy/.local/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.7/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/haojy/.local/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/haojy/.local/lib/python3.7/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 86, in do_search_api
    ids,title, text, distances = search_in_milvus(table_name,query_sentence, MILVUS_CLI, MYSQL_CLI)
  File "/home/haojy/bootcamp-master/solutions/text_search_engine/quick_deploy/server/src/operations/search.py", line 35, in search_in_milvus
    results = milvus_cli.search_vectors(table_name,query_list,TOP_K)
  File "/home/haojy/bootcamp-master/solutions/text_search_engine/quick_deploy/server/src/milvus_helpers.py", line 106, in search_vectors
    sys.exit(1)
SystemExit: 1
INFO:     192.168.12.209:11149 - "GET /text/search?table_name=test_table&query_sentence=Google HTTP/1.1" **500 Internal Server Error**

### Software version

```markdown
Milvus: 2.0
Server: \bootcamp-master\solutions\text_search_engine\quick_deploy\server\src
Client: \bootcamp-master\solutions\text_search_engine\quick_deploy\client
```

**Comment by anykkk** [comment]
![image](https://user-images.githubusercontent.com/48540503/137473574-30b419a6-723c-423d-bd5b-250d76b8097f.png)
![image](https://user-images.githubusercontent.com/48540503/137473634-680446ba-1392-46f6-9ee0-2de193f6c657.png)

**Comment by anykkk** [comment]
pymilvus version 2.0.0rc5

======================================================
Keras==2.3.1
numpy
futures==3.1.1
cryptography
aiofiles
Pillow
pymilvus==2.0.0rc5
tensorflow == 1.13.1
bert-serving-server
bert-serving-client
pymysql
fastapi  
uvicorn
python-multipart

**Comment by jingkl** [comment]
the pymilvus version need to be same with milvus ,you need to install pymilvus 2.0.0rc7

**Comment by anykkk** [comment]
Thank you, it has been resolved!
