### ISSUE TITLE
[BUG]: Error with extracting feature from image list index out of range&&Failed to load data to Milvus: list index out of range

### ISSUE THREAD

**Issue by Yezi-cmd** [milvus-io/bootcamp#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use ‘Deploy with source code’ ，in webpage，I input my image path，and I watch log，many module are loading。But the internet changes, it is interrupt. So I restart milvus ,mysql, webserver and webclient. But Error:
      2021-11-19 16:49:06,378 ｜ ERROR ｜ task.py ｜ execute ｜ 119 ｜ pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>
2021-11-19 16:49:06,398 ｜ ERROR ｜ load.py ｜ extract_features ｜ 37 ｜ Error with extracting feature from image list index out of range
2021-11-19 16:49:06,421 ｜ ERROR ｜ milvus_helpers.py ｜ insert ｜ 72 ｜ Failed to load data to Milvus: list index out of range
ERROR:    Exception in ASGI application
   ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 65, in insert
    mr = self.collection.insert(data)
  File "/opt/venv/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 521, in insert
    if not self._check_insert_data_schema(data):
  File "/opt/venv/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 171, in _check_insert_data_schema
    infer_fields = parse_fields_from_data(data)
  File "/opt/venv/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 282, in parse_fields_from_data
    d_type = infer_dtype_bydata(d[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/opt/venv/lib/python3.8/site-packages/fastapi/routing.py", line 214, in app
    raw_response = await run_endpoint_function(
  File "/opt/venv/lib/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 70, in load_images
    total_num = do_load(item.Table, item.File, MODEL, MILVUS_CLI, MYSQL_CLI)
  File "/opt/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/operations/load.py", line 59, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/opt/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 73, in insert
    sys.exit(1)
SystemExit: 1
2021-11-19 16:49:06,421 ｜ ERROR ｜ h11_impl.py ｜ run_asgi ｜ 399 ｜ Exception in ASGI application
Traceback (most recent call last):
  File "/opt/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 65, in insert
    mr = self.collection.insert(data)
  File "/opt/venv/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 521, in insert
    if not self._check_insert_data_schema(data):
  File "/opt/venv/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 171, in _check_insert_data_schema
    infer_fields = parse_fields_from_data(data)
  File "/opt/venv/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 282, in parse_fields_from_data
    d_type = infer_dtype_bydata(d[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/opt/venv/lib/python3.8/site-packages/fastapi/routing.py", line 214, in app
    raw_response = await run_endpoint_function(
  File "/opt/venv/lib/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 70, in load_images
    total_num = do_load(item.Table, item.File, MODEL, MILVUS_CLI, MYSQL_CLI)
  File "/opt/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/operations/load.py", line 59, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/opt/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 73, in insert
    sys.exit(1)
SystemExit: 1

### Software version

```markdown
Milvus: [2.0.0rc8]
Server: [2.0.0]
Client: [2.0.0]
```

**Comment by jaelgu** [comment]
@Yezi-cmd Are you using the reverse_image_search WITHOUT object detection? Did you use the up-to-date codes?

It looks like that load failed.
- If you deployed with up-to-date source code (ie. run main.py to start api server), you should not start the webserver dock container.
- Check if your milvus server is up.
- If milvus is up, manually connect to milvus and check if the collection "milvus_img_search" is created successfully.

**Comment by Yezi-cmd** [comment]
> @Yezi-cmd Are you using the reverse_image_search WITHOUT object detection? Did you use the up-to-date codes?
> 
> It looks like that load failed.
> 
> * If you deployed with up-to-date source code (ie. run main.py to start api server), you should not start the webserver dock container.
> * Check if your milvus server is up.
> * If milvus is up, manually connect to milvus and check if the collection "milvus_img_search" is created successfully.

run main.py is not webserver dock container????

**Comment by Yezi-cmd** [comment]
> * milvus_img_search" is created successfully

When I run main.py, milvus_img_search is created successfully!

**Comment by jaelgu** [comment]
@Yezi-cmd A webserver docker container means a container created with image, the web server part is running in a docker container. However running source code `main.py` will start web server service without docker.

What is the data path that you entered in webclient webpage? Is that a folder path containing images in .jpg or .png?

**Comment by Yezi-cmd** [comment]
> @Yezi-cmd A webserver docker container means a container created with image, the web server part is running in a docker container. However running source code `main.py` will start web server service without docker.
> 
> What is the data path that you entered in webclient webpage? Is that a folder path containing images in .jpg or .png?

"However running source code main.py will start web server service without docker."  How to do??  Should I start a docker of webServer?

**Comment by Yezi-cmd** [comment]
> @Yezi-cmd A webserver docker container means a container created with image, the web server part is running in a docker container. However running source code `main.py` will start web server service without docker.
> 
> What is the data path that you entered in webclient webpage? Is that a folder path containing images in .jpg or .png?

The folder path containing images in .jpg.

**Comment by jaelgu** [comment]
@Yezi-cmd
- You only need to use 1 option to start web server service: docker container OR main.py
- Have you modified config.py? Can you share it?

**Comment by jaelgu** [comment]
@Yezi-cmd Also please make sure that you use the absolute path and ONLY images in that folder without files in other format. You can check with command `ls -a` to see what files in the directory.

**Comment by Yezi-cmd** [comment]
> 

I know your meaning. I start with main.py only. Here are my config.py:

import os

############### Milvus Configuration ###############
MILVUS_HOST = os.getenv("MILVUS_HOST", "192.168.1.122")
MILVUS_PORT = int(os.getenv("MILVUS_PORT", "19530"))
VECTOR_DIMENSION = int(os.getenv("VECTOR_DIMENSION", "1000"))
INDEX_FILE_SIZE = int(os.getenv("INDEX_FILE_SIZE", "1024"))
METRIC_TYPE = os.getenv("METRIC_TYPE", "L2")
DEFAULT_TABLE = os.getenv("DEFAULT_TABLE", "milvus_img_search")
TOP_K = int(os.getenv("TOP_K", "10"))

############### MySQL Configuration ###############
MYSQL_HOST = os.getenv("MYSQL_HOST", "192.168.1.122")
MYSQL_PORT = int(os.getenv("MYSQL_PORT", "3306"))
MYSQL_USER = os.getenv("MYSQL_USER", "root")
MYSQL_PWD = os.getenv("MYSQL_PWD", "123456")
MYSQL_DB = os.getenv("MYSQL_DB", "mysql")

############### Data Path ###############
UPLOAD_PATH = os.getenv("UPLOAD_PATH", "tmp/search-images")

############### Number of log files ###############
LOGS_NUM = int(os.getenv("logs_num", "0"))

**Comment by Yezi-cmd** [comment]
> 

I know your meaning. I start with main.py only. Here are my config.py:

import os

############### Milvus Configuration ###############
MILVUS_HOST = os.getenv("MILVUS_HOST", "192.168.1.122")
MILVUS_PORT = int(os.getenv("MILVUS_PORT", "19530"))
VECTOR_DIMENSION = int(os.getenv("VECTOR_DIMENSION", "1000"))
INDEX_FILE_SIZE = int(os.getenv("INDEX_FILE_SIZE", "1024"))
METRIC_TYPE = os.getenv("METRIC_TYPE", "L2")
DEFAULT_TABLE = os.getenv("DEFAULT_TABLE", "milvus_img_search")
TOP_K = int(os.getenv("TOP_K", "10"))

############### MySQL Configuration ###############
MYSQL_HOST = os.getenv("MYSQL_HOST", "192.168.1.122")
MYSQL_PORT = int(os.getenv("MYSQL_PORT", "3306"))
MYSQL_USER = os.getenv("MYSQL_USER", "root")
MYSQL_PWD = os.getenv("MYSQL_PWD", "123456")
MYSQL_DB = os.getenv("MYSQL_DB", "mysql")

############### Data Path ###############
UPLOAD_PATH = os.getenv("UPLOAD_PATH", "tmp/search-images")

############### Number of log files ###############
LOGS_NUM = int(os.getenv("logs_num", "0"))

**Comment by Yezi-cmd** [comment]
> @Yezi-cmd
> 
> * You only need to use 1 option to start web server service: docker container OR main.py
> * Have you modified config.py? Can you share it?

I know your meaning. I start with main.py only. Here are my config.py:

import os

############### Milvus Configuration ###############
MILVUS_HOST = os.getenv("MILVUS_HOST", "192.168.1.122")
MILVUS_PORT = int(os.getenv("MILVUS_PORT", "19530"))
VECTOR_DIMENSION = int(os.getenv("VECTOR_DIMENSION", "1000"))
INDEX_FILE_SIZE = int(os.getenv("INDEX_FILE_SIZE", "1024"))
METRIC_TYPE = os.getenv("METRIC_TYPE", "L2")
DEFAULT_TABLE = os.getenv("DEFAULT_TABLE", "milvus_img_search")
TOP_K = int(os.getenv("TOP_K", "10"))

############### MySQL Configuration ###############
MYSQL_HOST = os.getenv("MYSQL_HOST", "192.168.1.122")
MYSQL_PORT = int(os.getenv("MYSQL_PORT", "3306"))
MYSQL_USER = os.getenv("MYSQL_USER", "root")
MYSQL_PWD = os.getenv("MYSQL_PWD", "123456")
MYSQL_DB = os.getenv("MYSQL_DB", "mysql")

############### Data Path ###############
UPLOAD_PATH = os.getenv("UPLOAD_PATH", "tmp/search-images")

############### Number of log files ###############
LOGS_NUM = int(os.getenv("logs_num", "0"))

**Comment by Yezi-cmd** [comment]
> @Yezi-cmd Also please make sure that you use the absolute path and ONLY images in that folder without files in other format. You can check with command `ls -a` to see what files in the directory.

I make sure that I use the absolute path and ONLY images in that folder .

**Comment by holmofy** [comment]
hi. is this problem solved? I also encountered this problem.

I am using the docker container, not the source code.

```yaml
  etcd: ...
  minio: ...
  milvus:
    image: milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - 19530:19530
    depends_on:
      - etcd
      - minio

  webserver:
    image: milvusbootcamp/img-search-server:towhee
    environment:
      MILVUS_HOST: 'milvus'
      MYSQL_HOST: "172.17.0.11"
      MYSQL_PORT: 3306
      MYSQL_PWD: xudjf23adj213
      MYSQL_DB: milvus
    volumes:
      - ./images:/data
    restart: always
    depends_on:
      - milvus
    ports:
      - 5000:5000

  webclient:
    image: milvusbootcamp/img-search-client:1.0
    environment:
      API_URL: 'http://127.0.0.1:5000'
    ports:
      - 8001:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8001"]
      interval: 30s
      timeout: 20s
      retries: 3
```

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
