### ISSUE TITLE
[BUG]: in audio similarity search, audio webserver fails to load all the audio files when one of the files has too short duration

### ISSUE THREAD

**Issue by aharonh** [milvus-io/bootcamp#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I clink on upload button while in /audio-data folder is at least one short duration audio file, the whole data import fails.

The log line that appears due to small audio file:

`
2021-12-31 14:57:59,038 ｜ ERROR ｜ encode.py ｜ get_audio_embedding ｜ 17 ｜ Error with embedding:Given input size: (512x1x8). Calculated output size: (512x0x4). Output size is too small
`

After completing feature extraction, the insert method of milvus_helpers.py fails with following exception 

```
Extracting feature from audio No. 102 , 107 audios in total
Checkpoint path: /root/panns_data/Cnn14_mAP=0.431.pth
Using CPU.
Extracting feature from audio No. 103 , 107 audios in total
Checkpoint path: /root/panns_data/Cnn14_mAP=0.431.pth
Using CPU.
2021-12-31 17:38:55,734 ｜ ERROR ｜ encode.py ｜ get_audio_embedding ｜ 17 ｜ Error with embedding:Given input size: (512x1x8). Calculated output size: (512x0x4). Output size is too small
Extracting feature from audio No. 104 , 107 audios in total
Checkpoint path: /root/panns_data/Cnn14_mAP=0.431.pth
Using CPU.
2021-12-31 17:38:57,277 ｜ ERROR ｜ encode.py ｜ get_audio_embedding ｜ 17 ｜ Error with embedding:Given input size: (256x1x16). Calculated output size: (256x0x8). Output size is too small
Extracting feature from audio No. 105 , 107 audios in total
Checkpoint path: /root/panns_data/Cnn14_mAP=0.431.pth
Using CPU.
2021-12-31 17:38:58,848 ｜ ERROR ｜ encode.py ｜ get_audio_embedding ｜ 17 ｜ Error with embedding:Given input size: (1024x1x4). Calculated output size: (1024x0x2). Output size is too small
Extracting feature from audio No. 106 , 107 audios in total
Checkpoint path: /root/panns_data/Cnn14_mAP=0.431.pth
Using CPU.
2021-12-31 17:39:00,410 ｜ ERROR ｜ encode.py ｜ get_audio_embedding ｜ 17 ｜ Error with embedding:Given input size: (1024x1x4). Calculated output size: (1024x0x2). Output size is too small
Extracting feature from audio No. 107 , 107 audios in total
2021-12-31 17:39:00,474 ｜ ERROR ｜ milvus_helpers.py ｜ insert ｜ 72 ｜ Failed to load data to Milvus: <DataNotMatchException: (code=0, message=The data in the same column must be of the same type.)>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/src/milvus_helpers.py", line 65, in insert
    mr = self.collection.insert(data)
  File "/usr/local/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 521, in insert
    if not self._check_insert_data_schema(data):
  File "/usr/local/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 181, in _check_insert_data_schema
    _check_data_schema(infer_fields, data)
  File "/usr/local/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 69, in _check_data_schema
    raise DataNotMatchException(0, ExceptionsMessage.DataTypeInconsistent)
pymilvus.orm.exceptions.DataNotMatchException: <DataNotMatchException: (code=0, message=The data in the same column must be of the same type.)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/src/main.py", line 67, in load_audios
    total_num = do_load(item.Table, item.File, MILVUS_CLI, MYSQL_CLI)
  File "/app/src/operations/load.py", line 52, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/app/src/milvus_helpers.py", line 73, in insert
    sys.exit(1)
SystemExit: 1
2021-12-31 17:39:00,474 ｜ ERROR ｜ h11_impl.py ｜ run_asgi ｜ 376 ｜ Exception in ASGI application
Traceback (most recent call last):
  File "/app/src/milvus_helpers.py", line 65, in insert
    mr = self.collection.insert(data)
  File "/usr/local/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 521, in insert
    if not self._check_insert_data_schema(data):
  File "/usr/local/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 181, in _check_insert_data_schema
    _check_data_schema(infer_fields, data)
  File "/usr/local/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 69, in _check_data_schema
    raise DataNotMatchException(0, ExceptionsMessage.DataTypeInconsistent)
pymilvus.orm.exceptions.DataNotMatchException: <DataNotMatchException: (code=0, message=The data in the same column must be of the same type.)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/src/main.py", line 67, in load_audios
    total_num = do_load(item.Table, item.File, MILVUS_CLI, MYSQL_CLI)
  File "/app/src/operations/load.py", line 52, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/app/src/milvus_helpers.py", line 73, in insert
    sys.exit(1)
SystemExit: 1
INFO:     172.16.23.1:54016 - "POST /audio/load HTTP/1.1" 500 Internal Server Error

```

None of the audio files is available for search.

### Expected Behavior

The data loads as expected, skipping the short files that are too short to index.

### Steps To Reproduce

```markdown
dock-compose up -d -f audiosearch-docker-compose.yaml

Make sure to place at least one short audio file (for example 0.8 seconds audio file.) in the data folder and then, open up the browser at http://172.16.23.13/ type '/audio_data' and press upload button.
```

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
Thanks @aharonh and it merged :)

**Comment by aharonh** [comment]
Thanks @shiyu22 , closing.
